
[pytest]
testpaths =
    tests

addopts =
    -v
    -rA
    -s
    --html=reports/report.html
    --self-contained-html
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --alluredir=allure-results